[preload  storage="./data/bgimage/01_minato.png"  ]
[preload  storage="./data/fgimage/chara/1/nagisa_normal.png"  ]
[preload  storage="./data/fgimage/chara/3/taiyou_smail2.png"  ]
[preload  storage="./data/fgimage/chara/1/nagisa_smile.png"  ]
[preload  storage="./data/fgimage/chara/3/taiyou_normal.png"  ]
[preload  storage="./data/fgimage/chara/1/nagisa_odoroki.png"  ]
[preload  storage="./data/fgimage/chara/3/taiyou_smail.png"  ]
[preload  storage="./data/fgimage/chara/1/nagisa_sune.png"  ]
[return]