[preload  storage="./data/bgimage/01_bouhatei.png"  ]
[preload  storage="./data/fgimage/chara/1/nagisa_sune.png"  ]
[preload  storage="./data/fgimage/chara/1/nagisa_normal.png"  ]
[preload  storage="./data/fgimage/chara/1/nagisa_odoroki.png"  ]
[preload  storage="./data/fgimage/chara/1/nagisa_smile.png"  ]
[preload  storage="./data/fgimage/chara/1/nagisa_odoroki2.png"  ]
[preload  storage="./data/bgimage/01_hayashi.png"  ]
[preload  storage="./data/fgimage/chara/1/nagisa_ikari.png"  ]
[return]