[preload  storage="./data/bgimage/04_tosho.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_sune.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_normal.png"  ]
[preload  storage="./data/bgimage/04_shiryoushitsu.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_cold.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_akire.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_kanshin.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_smile.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_ureshii.png"  ]
[return]