[preload  storage="./data/bgimage/07_shosai.png"  ]
[preload  storage="./data/fgimage/default/pc.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_akire.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_normal.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_kanshin.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_konwaku.png"  ]
[return]