[preload  storage="./data/bgimage/07_shosai_yuugata.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_kanshin.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_normal.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_akire.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_cold.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_konwaku.png"  ]
[preload  storage="./data/fgimage/chara/9/rika_smile.png"  ]
[preload  storage="./data/bgimage/07_shosai_yoru.png"  ]
[preload  storage="./data/fgimage/default/techou.png"  ]
[return]